
using Zenject;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SystemsGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Ecs.Installers {
	public static class GameEcsSystems {
		public static void Install(DiContainer container){
		}

	}
}